---
title: "NYC Restaurant Inspections from 2016"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE, eval = F}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets) # no longer available
library(plotly)
```


```{r, eval = F}
#tidy data

set.seed(88)

rest_inspection_data = rest_inspec %>%
  separate(inspection_date, into = c("year", "month", "day"), sep = "-") %>%
  mutate(year = as.integer(year), month = as.integer(month), day = as.integer(day),
         cuisine_description = factor(cuisine_description)) %>%
  filter(year == 2016) %>% #filter out reviews from 2016
  sample_n(5000) #randomly select observations to make better plots

```


Column {data-width=500}
-----------------------------------------------------------------------

###Grade Breakdown

```{r, eval = F}
#create bar chart demonstrating percent received each grade per boro

rest_inspection_data %>%
  mutate(grade = factor(grade),
         boro = factor(boro)) %>%
  group_by(boro, grade) %>%
  count(grade) %>%
  group_by(boro) %>%
  mutate(total = sum(n),
         grade_perc = round(n/total, 2)) %>%
  select(-n, total) %>%
  spread(key = grade, value = grade_perc) %>%
  rename(missing = `<NA>`, no_grade = `Not Yet Graded`) %>%
  replace_na(list(A = 0, B = 0, C = 0, no_grade = 0, P = 0, Z = 0, missing = 0)) %>%
  ungroup(boro) %>%
  mutate(boro = fct_reorder(boro, A)) %>% 
  plot_ly(x = ~A, y = ~boro, type = 'bar', orientation = 'h', name = 'A') %>%
  add_trace(x = ~B, y = ~boro, type = 'bar', orientation = 'h', name = 'B') %>%
  add_trace(x = ~C, y = ~boro, type = 'bar', orientation = 'h', name = 'C') %>%
  add_trace(x = ~P, y = ~boro, type = 'bar', orientation = 'h', name = 'P') %>%
  add_trace(x = ~missing, y = ~boro, type = 'bar', orientation = 'h', name = 'Missing') %>%
  layout(barmode = 'stack',
         xaxis = list(title = "Percent"),
         yaxis = list(title = ""))



```

Column {data-width=500}
-----------------------------------------------------------------------

###Inspection Results

```{r, eval = F}
#boxplots to show distribution of scores per boro

rest_inspection_data %>%
  mutate(boro = fct_reorder(boro, score)) %>% 
  plot_ly(y = ~score, color = ~boro, type = "box", colors = "Set2") %>%
  layout(xaxis = list(title = ""),
         yaxis = list(title = 'Score'))
```

### Inspections per Month

```{r, eval = F}
#Check how frequent retaurants were inspected per month in 2016

rest_inspection_data %>%
  mutate(month = factor(month),
         month = month.name[month],
         month = forcats::fct_relevel(month, "January", "February", "March", "April", "May",
                                      "June", "July", "August", "September", "October", 
                                      "November", "December")) %>%
  count(month) %>%
  plot_ly(x = ~month, y = ~n, type = 'scatter', mode = 'lines') %>%
  layout(xaxis = list(title = "", tickangle = 270),
         yaxis = list(title = 'Count',
                      range = c(0,550)))

```
